### ISSUE TITLE
Documentation for aci.bicep

### ISSUE THREAD

**Issue by jakobsuckow** [sharmavikashkr/azure-test#1]
Hi,
Really like your repo as I am also in need to run a dockerized nestjs app in aci. Could you add some more steps in the readme file that explain the presence of the the aci.bicep file ? 
Cheers

**Comment by sharmavikashkr** [comment]
Sure. This is definitely pending on my part. Will add the readme shortly.

**Comment by sharmavikashkr** [comment]
Done. You can see all the details now.

**Comment by jakobsuckow** [comment]
Thanks :)
